# 完整配置: https://github.com/seata/seata/blob/develop/script/client/spring/application.yml
seata:
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: false
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      namespace: ""
      username: nacos
      password: nacos
      application: seata-server # 注意这个，跟seata-server的服务名要一致的
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      namespace: ""
      username: nacos
      password: nacos
      data-id: seataClient.properties
  tx-service-group: default_tx_group